apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dview-webui 
  name: dview-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dview-webui
  template:
    metadata:
      labels:
        app: dview-webui 
    spec:
      containers:
        - image: quay.io/dviewquay/dvmobile
          imagePullPolicy: Always
          name: dview-webui
          ports:
            - containerPort: 9080
              protocol: TCP
            - containerPort: 9443
              protocol: TCP
      imagePullSecrets:
        - name: quay-pull-secret
