apiVersion: v1
kind: Service
metadata:
  labels:
    app: dview-webui
  name: dview-webui-service
spec:
  type: NodePort
  ports:
    - name: 9443-tcp
      port: 9443
      targetPort: 9443
      protocol: TCP
    - name: 9080-tcp
      port: 9080
      targetPort: 9080
      protocol: TCP
  selector:
    app: dview-webui
